In [2]:
import pandas as pd
import numpy as np

In [3]:
!pwd

/Users/joshua/Development/business-analysis/Tutorials


In [4]:
%cd ../Data

/Users/joshua/Development/business-analysis/Data


In [5]:
!ls

customer_data.xlsx	     sales_data_sample.xlsx
part_usage_trailing_12.xlsx  sales_data_sample_no_customer.xlsx
sales_data_sample.csv


In [6]:
sales_data = pd.read_excel('sales_data_sample.xlsx')

In [7]:
sales_data.head()

ORDERNUMBER  QUANTITYORDERED  PRICEEACH  ORDERLINENUMBER    SALES  \
0        10107               30      95.70                2  2871.00   
1        10121               34      81.35                5  2765.90   
2        10134               41      94.74                2  3884.34   
3        10145               45      83.26                6  3746.70   
4        10159               49     100.00               14  5205.27   

   ORDERDATE   STATUS  QTR_ID  MONTH_ID  YEAR_ID   ...     \
0 2003-02-24  Shipped       1         2     2003   ...      
1 2003-05-07  Shipped       2         5     2003   ...      
2 2003-07-01  Shipped       3         7     2003   ...      
3 2003-08-25  Shipped       3         8     2003   ...      
4 2003-10-10  Shipped       4        10     2003   ...      

                    ADDRESSLINE1  ADDRESSLINE2           CITY STATE  \
0        897 Long Airport Avenue           NaN            NYC    NY   
1             59 rue de l'Abbaye           NaN          Reims   NaN   
2  27 rue du Colonel Pierre Avia           NaN          Paris   NaN   
3             78934 Hillside Dr.           NaN       Pasadena    CA   
4                7734 Strong St.           NaN  San Francisco    CA   

  POSTALCODE COUNTRY TERRITORY CONTACTLASTNAME CONTACTFIRSTNAME DEALSIZE  
0      10022     USA       NaN              Yu             Kwai    Small  
1      51100  France      EMEA         Henriot             Paul    Small  
2      75508  France      EMEA        Da Cunha           Daniel   Medium  
3      90003     USA       NaN           Young            Julie   Medium  
4        NaN     USA       NaN           Brown            Julie   Medium  

[5 rows x 25 columns]

In [9]:
prices = np.array(sales_data["PRICEEACH"])
quantities = np.array(sales_data["QUANTITYORDERED"])

In [13]:
prices

array([ 95.7 ,  81.35,  94.74, ..., 100.  ,  62.24,  65.52])

In [14]:
quantities

array([30, 34, 41, ..., 43, 34, 47])

In [15]:
line_totals = prices * quantities

In [16]:
line_totals

array([2871.  , 2765.9 , 3884.34, ..., 4300.  , 2116.16, 3079.44])

In [28]:
sales_data.columns.get_loc("SALES")

4

In [34]:
sales_data.iloc[0,4] == line_totals[0]

True

In [35]:
line_totals.sum()

8290886.789999999

In [36]:
def sumproduct(dataframe, column_1_label, column_2_label):
    column_1 = np.array(dataframe[column_1_label])
    column_2 = np.array(dataframe[column_2_label])
    line_totals = column_1 * column_2
    return line_totals.sum()

In [37]:
sumproduct(sales_data, "PRICEEACH", "QUANTITYORDERED")

8290886.789999999