In [1]:
import numpy as np

### Indexing and Slicing

In [16]:
integer_array = np.arange(15)

In [17]:
integer_array = integer_array[::-1]
integer_array

array([14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

#### Pulling a value (Indexing)

In [18]:
integer_array[0]

14

In [19]:
integer_array[2]

12

In [20]:
integer_array[-1]

0

#### Pulling multiple values (slicing)

In [21]:
integer_array[:3]

array([14, 13, 12])

In [22]:
integer_array[3:]

array([11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [23]:
integer_array[1:3]

array([13, 12])

In [25]:
integer_array[1:3] = 0
integer_array

array([14,  0,  0, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

#### Modifying Slice Data

In [27]:
integer_slice = integer_array[1:3]
integer_slice[0] = 13
integer_array

array([14, 13,  0, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])